-- ==========================================================
-- PostgreSQL Database Schema for Inventory Management System
-- ==========================================================

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Color" character varying(50) NOT NULL DEFAULT 'purple',
    "Icon" character varying(50) NOT NULL DEFAULT 'FolderTree',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Categories_Name" ON "Categories" ("Name");

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Sku" character varying(50) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "CategoryId" integer NOT NULL REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    "Price" numeric(18,2) NOT NULL,
    "StockQuantity" integer NOT NULL DEFAULT 0,
    "LowStockThreshold" integer NOT NULL DEFAULT 5,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Sku" ON "Products" ("Sku");
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON "Products" ("CategoryId");

-- 3. Create StockMovements Audit Table
CREATE TABLE IF NOT EXISTS "StockMovements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductId" integer NOT NULL REFERENCES "Products" ("Id") ON DELETE CASCADE,
    "MovementType" integer NOT NULL, -- 1: StockIn, 2: StockOut
    "Quantity" integer NOT NULL,
    "BalanceBefore" integer NOT NULL,
    "BalanceAfter" integer NOT NULL,
    "Remarks" character varying(500),
    "Timestamp" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_StockMovements_ProductId" ON "StockMovements" ("ProductId");

-- ==========================================================
-- Sample Seed Data
-- ==========================================================
INSERT INTO "Categories" ("Name", "Description", "Color", "Icon", "CreatedAt")
VALUES 
    ('Electronics', 'Gadgets, peripherals, and audio devices', 'blue', 'Laptop', CURRENT_TIMESTAMP),
    ('Office Furniture', 'Ergonomic desks, chairs, and mounts', 'amber', 'Armchair', CURRENT_TIMESTAMP),
    ('Beverages & Pantry', 'Artisan coffees, teas, and snacks', 'orange', 'Coffee', CURRENT_TIMESTAMP),
    ('Cables & Accessories', 'High-speed data and charging cords', 'purple', 'Cable', CURRENT_TIMESTAMP)
ON CONFLICT ("Name") DO NOTHING;

INSERT INTO "Products" ("Sku", "Name", "Description", "CategoryId", "Price", "StockQuantity", "LowStockThreshold", "CreatedAt")
VALUES 
    ('TECH-001', 'Ultra-Slim Mechanical Keyboard (RGB)', 'Hot-swappable tactile switches with wireless Bluetooth 5.2', 1, 119.99, 42, 10, CURRENT_TIMESTAMP),
    ('TECH-002', 'Precision Wireless Ergonomic Mouse', '4000 DPI sensor with silent click buttons', 1, 59.50, 18, 10, CURRENT_TIMESTAMP),
    ('TECH-003', '27" 4K UHD IPS Monitor', '144Hz refresh rate, USB-C 90W power delivery', 1, 349.00, 3, 5, CURRENT_TIMESTAMP),
    ('TECH-004', 'Noise-Cancelling Over-Ear Headphones', 'Active noise cancellation with 35hr battery life', 1, 199.99, 0, 5, CURRENT_TIMESTAMP),
    ('FURN-001', 'Ergonomic Mesh Task Chair', 'Adjustable lumbar support and 3D armrests', 2, 289.00, 14, 5, CURRENT_TIMESTAMP),
    ('FURN-002', 'Electric Dual-Motor Standing Desk', '140x70cm oak tabletop with memory presets', 2, 449.00, 4, 5, CURRENT_TIMESTAMP),
    ('BEV-001', 'Artisan Roast Whole Bean Coffee (1kg)', 'Single origin Ethiopian Yirgacheffe medium roast', 3, 24.50, 55, 15, CURRENT_TIMESTAMP),
    ('BEV-002', 'Organic Japanese Ceremonial Matcha (100g)', 'First harvest stone-ground green tea powder', 3, 32.00, 22, 10, CURRENT_TIMESTAMP),
    ('CAB-001', 'Braided Thunderbolt 4 Cable (2m)', '40Gbps transfer speed and 100W PD charging', 4, 29.99, 68, 20, CURRENT_TIMESTAMP),
    ('CAB-002', '100W GaN 4-Port Fast Charger', '3x USB-C and 1x USB-A ultra-compact travel plug', 4, 49.99, 2, 8, CURRENT_TIMESTAMP)
ON CONFLICT ("Sku") DO NOTHING;
